package:
  name: astropy
  version: 5.1.1
  top-level:
    - astropy
source:
  url: https://files.pythonhosted.org/packages/ce/02/213096b189211a750d21d48d18d945efa6c8a334134a6f01b8f2d2fd4b2d/astropy-5.1.1.tar.gz
  sha256: ba4bd696af7090fd399b464c704bf27b5633121e461785edc70432606a94bd81
build:
  # The test module is imported from the top level `__init__.py`
  # so it cannot be unvendored
  unvendor-tests: false
  exports: requested # Astropy uses dlsym so we need to export more than just PyInit_astropy
  cflags: |
    -I $(HOSTSITEPACKAGES)/numpy/core/include
requirements:
  host:
    - packaging
    - numpy
  run:
    - distutils
    - packaging
    - numpy
    - pyerfa
    - pyyaml
test:
  imports:
    - astropy
    - astropy.config
    - astropy.constants
    - astropy.convolution
    - astropy.coordinates
    - astropy.cosmology
    - astropy.extern
    - astropy.io
    - astropy.modeling
    - astropy.nddata
    - astropy.samp
    - astropy.stats
    - astropy.table
    - astropy.time
    - astropy.timeseries
    - astropy.uncertainty
    - astropy.units
    - astropy.utils
    - astropy.visualization
    - astropy.wcs
about:
  home: http://astropy.org
  PyPI: https://pypi.org/project/astropy
  summary: Astronomy and astrophysics core library
  license: BSD 3-Clause License
